FROM python:3.10-slim-bullseye

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY requirements requirements

RUN apt-get -qq update && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements/development.txt