# Generated by Django 5.1 on 2024-11-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_challenge_course_student_studentprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprogress",
            name="last_challenge_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                ],
                default=1,
            ),
        ),
    ]
