# Generated by Django 5.1 on 2024-11-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_studentprogress_last_challenge_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="challenges",
            field=models.ManyToManyField(related_name="courses", to="core.challenge"),
        ),
    ]
