# Generated by Django 5.1 on 2024-11-04 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_challenge_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="challenges",
        ),
        migrations.AddField(
            model_name="challenge",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="core.course",
            ),
        ),
    ]
