# Generated by Django 5.1 on 2024-11-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_challengestat"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengestat",
            name="timeout",
            field=models.BooleanField(default=False),
        ),
    ]
