# Generated by Django 5.1 on 2024-11-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_spacedrepetition"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_teacher",
            field=models.BooleanField(default=False),
        ),
    ]
