# Generated by Django 5.1 on 2024-11-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_challenge_is_active_student_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
