# Generated by Django 5.1 on 2024-11-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_student_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengestat",
            name="moment",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "No Moment"),
                    (1, "First Moment"),
                    (2, "Second Moment"),
                    (3, "Third Moment"),
                ],
                default=0,
            ),
        ),
    ]
